# Based on https://github.com/zeromq/zeromq-buildbot/blob/master/.travis.yml

language: python

matrix:
  fast_finish: true
  include:
   - env: TASK='flake8'
   - python: "2.7"
     env: TASK='pychecker'
   - python: "2.7"
     env: TASK='checkconfig'
#   - python: "3.2" # buildbot does not currently support Python 3
#     env: TASK='checkconfig'
#  - python: "3.3" # buildbot does not currently support Python 3
#     env: TASK='checkconfig'
#  - python: "pypy" # issues with travis halting during buildbot setup
#     env: TASK='checkconfig'

script:
  - "bash -ex .travis-ci.sh"

install:
  - sudo apt-get install -qq buildbot
  - if [ "$TASK" = "flake8" ]; then sudo pip install flake8; fi
# If this causes SSL errors, then Sourceforge is probably in disaster recovery mode and needing Javascript. Could switch to a specific mirror, e.g. kent.dl.sourceforge.net
  - if [ "$TASK" = "pychecker" ]; then sudo pip install --verbose http://sourceforge.net/projects/pychecker/files/pychecker/0.8.19/pychecker-0.8.19.tar.gz/download; fi
  - if [ "$TASK" = "pychecker" ]; then sudo updatedb && locate checker.py; fi
# This is a very bodgy workaround to the fact that the pip install of the archive doesn't seem to work properly now on Travis
  - if [ "$TASK" = "pychecker" ]; then sudo mkdir -p /pychecker/; sudo ln -s /home/travis/.local/lib/python2.7/site-packages/pychecker/checker.py /pychecker/checker.py; fi

#notifications:
#  irc:
#    channels:
#     - "chat.freenode.net#openlighting"
#    on_success: change
#    on_failure: change
